server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: service-feign

#自带熔断器，D版本的Spring Cloud之后默认关闭
feign:
  hystrix:
    enabled: true
