server:
  port: 8766
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yesyoungbaby/springcloud-learning #配置git仓库地址
          searchPaths: config-repo #配置仓库路径
        #  username: yesyoungbaby #访问git仓库的用户名
        # password: 649304hyy #访问git仓库的用户密码
      label: master #配置仓库的分支